// Generated by CoffeeScript 2.0.2
(function() {
  var Square, create, game, preload, update;

  game = new Phaser.Game(800, 600, Phaser.AUTO, '', {
    preload: preload,
    create: create,
    update: update
  });

  Square = class Square {
    constructor() {
      x * x;
    }

  };

  function preload () {
  
};

  function create (){
  preload()
};

  function update () {

};

  preload = function() {
    return console.log('haha');
  };

  create = function() {};

  update = function() {};

}).call(this);

//# sourceMappingURL=main.js.map
