// Generated by CoffeeScript 2.0.2
(function() {
  var Square, game;

  game = new Phaser.Game(800, 600, Phaser.AUTO, '', {
    preload: preload,
    create: create,
    update: update
  });

  Square = class Square {
    constructor() {
      x * x;
    }

  };

  function preload () {};

  function create (){};

  function update ();

  // preload = () ->

// create = () ->

// update = () ->

}).call(this);

//# sourceMappingURL=main.js.map
